name: Build and Analyze with SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest  # зміна тут

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # важливо для Sonar, щоб бачити всю git-історію

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and analyze with Maven
        working-directory: ./Back-End/demo
        run: >
          mvn clean verify -DskipTests=true sonar:sonar
          -Dsonar.projectKey=Vladosichek_DreamTire
          -Dsonar.organization=vladosichek
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
